# Generated by Django 5.2.11 on 2026-02-04 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Administration",
                "verbose_name_plural": "Administration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnneeAcademique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Année académique",
                "verbose_name_plural": "Années académiques",
                "db_table": "annees_academiques",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("contenu", models.TextField()),
                ("categorie", models.CharField(default="INFORMATION", max_length=20)),
                (
                    "fichier_joint",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("destinataires_tous", models.BooleanField(default=False)),
                (
                    "destinataires_roles",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("statut", models.CharField(default="BROUILLON", max_length=15)),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                ("envoi_email", models.BooleanField(default=True)),
                ("envoi_notification", models.BooleanField(default=True)),
                ("affichage_tableau", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "db_table": "annonces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icone", models.CharField(blank=True, max_length=50, null=True)),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("libelle", models.CharField(max_length=200)),
                ("effectif_max", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationRessource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_telecharge", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consultation Ressource",
                "verbose_name_plural": "Consultations Ressources",
                "db_table": "consultations_ressources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=10)),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("salle", models.CharField(blank=True, max_length=50, null=True)),
                ("type_seance", models.CharField(default="COURS", max_length=10)),
                ("date_debut_validite", models.DateField(blank=True, null=True)),
                ("date_fin_validite", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emploi du Temps",
                "verbose_name_plural": "Emplois du Temps",
                "db_table": "emplois_du_temps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_emprunt", models.CharField(default="EMPORTE", max_length=15)),
                ("date_emprunt", models.DateTimeField()),
                ("date_retour_prevue", models.DateField()),
                ("date_retour_effective", models.DateTimeField(blank=True, null=True)),
                ("statut", models.CharField(default="EN_COURS", max_length=15)),
                ("remarques", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emprunt",
                "verbose_name_plural": "Emprunts",
                "db_table": "emprunts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("type_evenement", models.CharField(default="AUTRE", max_length=20)),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "db_table": "evenements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exemplaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cote", models.CharField(max_length=50)),
                ("code_barres", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "emplacement",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("statut", models.CharField(default="DISPONIBLE", max_length=20)),
                ("date_entree", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exemplaire",
                "verbose_name_plural": "Exemplaires",
                "db_table": "exemplaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Filière",
                "verbose_name_plural": "Filières",
                "db_table": "filieres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_general", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Forum",
                "verbose_name_plural": "Forums",
                "db_table": "forums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureAnnonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lecture Annonce",
                "verbose_name_plural": "Lectures Annonces",
                "db_table": "lectures_annonces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("libelle", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("type_matiere", models.CharField(default="COURS", max_length=10)),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("credit", models.IntegerField(default=3)),
                ("semestre", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "db_table": "matieres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=300)),
                ("contenu", models.TextField()),
                (
                    "fichier_joint",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_lu", models.BooleanField(default=False)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2)),
                ("libelle", models.CharField(max_length=100)),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "db_table": "niveaux",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReactionReponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réaction",
                "verbose_name_plural": "Réactions",
                "db_table": "reactions_reponses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("nombre_likes", models.IntegerField(default=0)),
                ("is_solution", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
                "db_table": "reponses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statut", models.CharField(default="EN_ATTENTE", max_length=15)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                ("date_notification", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "db_table": "reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("type_ressource", models.CharField(max_length=15)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                ("editeur", models.CharField(blank=True, max_length=200, null=True)),
                ("annee_edition", models.IntegerField(blank=True, null=True)),
                ("date_soutenance", models.DateField(blank=True, null=True)),
                ("jury", models.TextField(blank=True, null=True)),
                ("resume", models.TextField(blank=True, null=True)),
                ("fichier", models.CharField(blank=True, max_length=500, null=True)),
                ("lien", models.URLField(blank=True, null=True)),
                ("taille_fichier", models.BigIntegerField(blank=True, null=True)),
                (
                    "format_fichier",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("auteur", models.CharField(blank=True, max_length=200, null=True)),
                ("date_publication", models.DateField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("nombre_vues", models.IntegerField(default=0)),
                ("nombre_telechargements", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ressource",
                "verbose_name_plural": "Ressources",
                "db_table": "ressources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sujet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("contenu", models.TextField()),
                ("is_epingle", models.BooleanField(default=False)),
                ("is_ferme", models.BooleanField(default=False)),
                ("is_resolu", models.BooleanField(default=False)),
                ("nombre_vues", models.IntegerField(default=0)),
                ("nombre_reponses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sujet",
                "verbose_name_plural": "Sujets",
                "db_table": "sujets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("couleur", models.CharField(default="#3B82F6", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdministrationEcole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20)),
                ("poste", models.CharField(max_length=30)),
                (
                    "departement",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bureau", models.CharField(blank=True, max_length=50, null=True)),
                ("peut_gerer_etudiants", models.BooleanField(default=True)),
                ("peut_gerer_enseignants", models.BooleanField(default=False)),
                ("peut_gerer_structure_academique", models.BooleanField(default=False)),
                ("peut_envoyer_annonces", models.BooleanField(default=True)),
                ("peut_gerer_bibliotheque", models.BooleanField(default=False)),
                ("peut_voir_statistiques", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_ecole_profile",
                        to="app_admin.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administration École",
                "verbose_name_plural": "Administration École",
                "db_table": "administration_ecole",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AffectationEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_intervention", models.CharField(default="COURS", max_length=10)),
                ("is_responsable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affectations_creees",
                        to="app_admin.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation Enseignant",
                "verbose_name_plural": "Affectations Enseignants",
                "db_table": "affectations_enseignants",
                "ordering": ["-created_at"],
            },
        ),
    ]
