# Generated by Django 5.2.13 on 2026-04-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_administrationecole_auth_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droitadministration',
            options={'ordering': ['ordre', 'domaine', 'action'], 'verbose_name': "Droit d'administration", 'verbose_name_plural': "Droits d'administration"},
        ),
    ]
