# Generated by Django 5.2.16 on 2026-09-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_droitadministration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='administration.classe'),
        ),
    ]
