# Generated by Django 4.2.27 on 2026-10-05 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0007_ressource_classe'),
        ('espace_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Cours', 'Cours'), ('TD', 'TD'), ('TP', 'TP'), ('Devoir', 'Devoir'), ('Examen', 'Examen'), ('Rapport', 'Rapport de stage ou mémoire'), ('Exercice', 'Exercice'), ('Annonce', 'Annonce'), ('Document', 'Document'), ('Autre', 'Autre')], max_length=20)),
                ('fichier', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('annee', models.CharField(blank=True, default='', max_length=9)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='administration.filiere')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='administration.matiere')),
            ],
            options={
                'db_table': 'library_documents',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='espace_library.librarydocument')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'library_download_history',
                'ordering': ['-date'],
            },
        ),
    ]
