# Generated by Django 5.2.11 on 2026-02-04 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("app_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prof",
                "verbose_name_plural": "Prof",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annee_academique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="administration.anneeacademique",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="administration.classe",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cours",
                        to="administration.matiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "db_table": "cours",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("ordre", models.IntegerField(default=0)),
                ("date_disponibilite", models.DateTimeField(blank=True, null=True)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres",
                        to="espace_prof.cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapitre",
                "verbose_name_plural": "Chapitres",
                "db_table": "chapitres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20)),
                ("grade", models.CharField(blank=True, max_length=20, null=True)),
                ("specialite", models.CharField(blank=True, max_length=200, null=True)),
                ("bureau", models.CharField(blank=True, max_length=50, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enseignant_profile",
                        to="app_admin.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Enseignants",
                "db_table": "enseignants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cours",
            name="enseignant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours",
                to="espace_prof.enseignant",
            ),
        ),
        migrations.CreateModel(
            name="Exercice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("enonce", models.TextField()),
                (
                    "fichier_enonce",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("corrige", models.TextField(blank=True, null=True)),
                (
                    "fichier_corrige",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "date_disponibilite_corrige",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercices",
                        to="espace_prof.chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice",
                "verbose_name_plural": "Exercices",
                "db_table": "exercices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("duree_minutes", models.IntegerField(default=30)),
                (
                    "note_sur",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("nombre_tentatives_max", models.IntegerField(default=1)),
                ("affiche_correction", models.BooleanField(default=True)),
                ("melange_questions", models.BooleanField(default=True)),
                ("date_ouverture", models.DateTimeField()),
                ("date_fermeture", models.DateTimeField()),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qcms",
                        to="espace_prof.chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "QCM",
                "verbose_name_plural": "QCMs",
                "db_table": "qcms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enonce", models.TextField()),
                ("type_question", models.CharField(default="UNIQUE", max_length=10)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="espace_prof.qcm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question QCM",
                "verbose_name_plural": "Questions QCM",
                "db_table": "questions_qcm",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReponseQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.CharField(max_length=500)),
                ("is_correcte", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="espace_prof.questionqcm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse QCM",
                "verbose_name_plural": "Réponses QCM",
                "db_table": "reponses_qcm",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RessourceCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("type_ressource", models.CharField(max_length=10)),
                ("fichier", models.CharField(blank=True, max_length=500, null=True)),
                ("lien", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ordre", models.IntegerField(default=0)),
                ("is_downloadable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ressources",
                        to="espace_prof.chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource de Cours",
                "verbose_name_plural": "Ressources de Cours",
                "db_table": "ressources_cours",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=300)),
                ("enonce", models.TextField()),
                ("consignes", models.TextField(blank=True, null=True)),
                (
                    "fichier_enonce",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date_limite", models.DateTimeField()),
                ("accepte_retard", models.BooleanField(default=False)),
                (
                    "penalite_retard",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("type_rendu", models.CharField(default="INDIVIDUEL", max_length=15)),
                ("taille_groupe_max", models.IntegerField(default=1)),
                (
                    "formats_acceptes",
                    models.CharField(default=".pdf,.zip,.py", max_length=200),
                ),
                ("taille_max_fichier", models.IntegerField(default=10)),
                (
                    "note_sur",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("bareme", models.TextField(blank=True, null=True)),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tps",
                        to="espace_prof.chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "TP",
                "verbose_name_plural": "TPs",
                "db_table": "tps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FichierSupportTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.CharField(max_length=500)),
                ("libelle", models.CharField(blank=True, max_length=200, null=True)),
                ("ordre", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichiers_support",
                        to="espace_prof.tp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier support TP",
                "verbose_name_plural": "Fichiers support TP",
                "db_table": "fichiers_support_tp",
                "ordering": ["-created_at"],
            },
        ),
    ]
