# Generated by Django 5.2.11 on 2026-02-04 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("app_admin", "0001_initial"),
        ("espace_prof", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Eleve",
                "verbose_name_plural": "Eleve",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=20)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "lieu_naissance",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("adresse", models.TextField(blank=True, null=True)),
                ("annee_entree", models.IntegerField(blank=True, null=True)),
                (
                    "contact_urgence_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_urgence_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etudiants",
                        to="administration.classe",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudiant_profile",
                        to="app_admin.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
                "db_table": "etudiants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RenduTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.CharField(max_length=500)),
                ("commentaire_etudiant", models.TextField(blank=True, null=True)),
                ("statut", models.CharField(default="RENDU", max_length=15)),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("commentaire_enseignant", models.TextField(blank=True, null=True)),
                (
                    "fichier_correction",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date_correction", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corrige_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tps_corriges",
                        to="espace_prof.enseignant",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendus_tp",
                        to="espace_student.etudiant",
                    ),
                ),
                (
                    "tp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendus",
                        to="espace_prof.tp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendu TP",
                "verbose_name_plural": "Rendus TP",
                "db_table": "rendus_tp",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TentativeQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tentative", models.IntegerField(default=1)),
                ("statut", models.CharField(default="EN_COURS", max_length=15)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "note_obtenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives_qcm",
                        to="espace_student.etudiant",
                    ),
                ),
                (
                    "qcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives",
                        to="espace_prof.qcm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative QCM",
                "verbose_name_plural": "Tentatives QCM",
                "db_table": "tentatives_qcm",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReponseEtudiantQCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correcte", models.BooleanField(default=False)),
                (
                    "points_obtenus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_etudiants",
                        to="espace_prof.questionqcm",
                    ),
                ),
                (
                    "tentative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_etudiant",
                        to="espace_student.tentativeqcm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse Étudiant QCM",
                "verbose_name_plural": "Réponses Étudiant QCM",
                "db_table": "reponses_etudiant_qcm",
                "ordering": ["-created_at"],
            },
        ),
    ]
