# Generated by Django 5.2.11 on 2026-09-16 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espace_student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionUploadEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "types_autorises",
                    models.JSONField(
                        default=list,
                        help_text="Liste de types : Cours, TD, TP, Devoir, Examen, Autre",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accorde_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_upload_accordees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_upload",
                        to="espace_student.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission upload étudiant",
                "verbose_name_plural": "Permissions upload étudiants",
                "db_table": "permissions_upload_etudiant",
                "ordering": ["-updated_at"],
            },
        ),
    ]
